countdown: 10
lobby-spawn:
    world: world
    x: 0
    y: 64
    z: 0
    yaw: 0
    pitch: 0
arenas:
  0:
    game: "ExampleGame1"
    required-players: 2
    max-players: 8
    world: world
    x: 0
    y: 64
    z: 0
    yaw: 0
    pitch: 0
  1:
    game: "ExampleGame2"
    required-players: 2
    max-players: 8
    world: world
    x: 0
    y: 64
    z: 0
    yaw: 0
    pitch: 0