required-players: 2
countdown: 10
lobby-spawn:
    world: world
    x: 0
    y: 64
    z: 0
    yaw: 0
    pitch: 0
arenas:
  0:
    world: world
    x: 0
    y: 64
    z: 0
    yaw: 0
    pitch: 0
  1:
    world: world
    x: 0
    y: 64
    z: 0
    yaw: 0
    pitch: 0